config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  root to: 'pages#index'
  get 'notes', to: "pages#notes", as: :notes
  get 'videos', to: "pages#videos", as: :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    	def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :password, :current_password)}
          end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def videos
  end

  def notes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BinaryBuddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light bg-light navbar-expand-lg">
      <div class="container-fluid">
        <%= image_tag("img.jpeg", :size=>"38x38", :class=>"me-2")%>
        <%= link_to "Binary Buddy", root_path, :class=>"navbar-brand"%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <div class="nav-item">
              <span class="nav-link active">Hello, <%= current_user.name %></span>
            </div>
          <% end %>
            <li class="nav-item">
              <%= link_to "Home", root_path, :class=>"nav-link active"%>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class=>"btn btn-warning"%>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, :class=>"btn btn-warning"%>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, :class=>"ms-2 btn btn-primary"%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-lg-12">
            <%= link_to "View Notes", notes_path, :class=>"btn btn-primary col-12" %>
        </div>

        <div class="col-lg-12 mt-3">
            <%= link_to "Watch Videos", videos_path, :class=>"btn btn-primary col-12" %>
        </div>

        <div class="col-lg-12 mt-3">
            <a href="https://www.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:digital-information/xcae6f4a7ff015e7d:binary-numbers/e/bits-and-binary-exercise" target="_blank" class="btn btn-primary col-12">Do Exercise</a>
        </div>

        <div class="col-lg-12 mt-3">
            <a href="https://take.quiz-maker.com/QHDHOF23B" target="_blank" class="btn btn-primary col-12">Participate Quiz</a>
        </div>
    </div>
</div>

app/views/pages/notes.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-lg-12">
            <a href="1.pdf" target="_blank" class="btn btn-primary col-12">BINARY NUMBER SYSTEM 1</a>
        </div>
        <div class="col-lg-12 mt-3">
            <a href="2.pdf" target="_blank" class="btn btn-primary col-12">BINARY NUMBER SYSTEM 2</a>
        </div>
        <div class="col-lg-12 mt-3">
            <a href="3.pdf" target="_blank" class="btn btn-primary col-12">BINARY NUMBER SYSTEM 3</a>
        </div>
        <div class="col-lg-12 mt-3">
            <a href="4.pdf" target="_blank" class="btn btn-primary col-12">BINARY NUMBER SYSTEM 4</a>
        </div>
    </div>
</div>

app/views/pages/videos.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-lg-6 text-center">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/FFDMzbrEXaE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col-lg-6 text-center">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/C5EkxfNEMjE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    <div class="row justify-content-center align-items-center mt-2">
        <div class="col-lg-6 text-center">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/rsxT4FfRBaM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col-lg-6 text-center">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/POwaKWZsZIw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>